# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

flutter_application_path = "../../../FlutterProject/myapp_flutter_module/flutter_module"
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'JHFlutterApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JHFlutterApp  
  install_all_flutter_pods(flutter_application_path)

end
